### ISSUE TITLE
ubuntu14 + Elasticsearch install

### ISSUE THREAD

**Issue by DangerView** [csirtgadgets/bearded-avenger#122]
Hi,

i'm try to install ubunt14/bootstrap_elasticsearch.sh 

but i saw this error

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "file (/home/cif/.cif.yml) is absent, cannot continue", "path": "/home/cif/.cif.yml", "state": "absent"}

how do i next step?

**Comment by DangerView** [comment]
input command : 
# cif-tokens --create 
Unable to read /root/.cif.yml config file

**Comment by wesyoung** [comment]
which release are you using?

**Comment by wesyoung** [comment]
fwiw; i've been fixing this in the fix/packaging tree:

https://github.com/csirtgadgets/bearded-avenger/compare/fix/packaging?expand=1
