### ISSUE TITLE
ES RawFields for fields like cc, city & tags

### ISSUE THREAD

**Issue by tk-hendrik** [csirtgadgets/bearded-avenger#152]
For a later Kibana Usage on CIF ES Instanse it would be great to have additional raw fields for cc, protocol, city and tags.
Background: Field Extraction of non-indexed fields (if I remember the kibana error-hint correctly) is heavy on heap mem and not really recommended.

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/bearded-avenger/blob/master/cif/store/zelasticsearch/indicator.py#L51

i think elasticsearch-dsl considers this a "Nested" type ?

http://elasticsearch-dsl.readthedocs.io/en/latest/persistence.html#mappings

https://github.com/csirtgadgets/bearded-avenger/blob/master/cif/store/zelasticsearch/indicator.py#L51

i had messed a little with it, but not enough to be confident...

**Comment by tk-hendrik** [comment]
Strings() from DSL will go to: 
```
          "tags" : {
            "type" : "text"
          },
```
If you try using "text" on Kibana it says:
`Visualize: Fielddata is disabled on text fields by default. Set fielddata=true on [tags] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.`

Further Reading:
https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html#_fielddata_is_disabled_on_literal_text_literal_fields_by_default

**Comment by tk-hendrik** [comment]
Thanks for merge
