### ISSUE TITLE
Submitting 1 indicator rapidly blocks for 5 seconds

### ISSUE THREAD

**Issue by JustinAzoff** [csirtgadgets/bearded-avenger#173]
The new batching code isn't 100% right yet.  It works for hunters I think since those just push and don't care about a response.  But when something submits 1 indicator at a time (like via zyre->cif gateway) the client ends up just waiting for the response which only happens after the 5 second flush.

I think nowait would fix this.

**Comment by wesyoung** [comment]
that's by design. but yes #161 should help the client out.

**Comment by wesyoung** [comment]
will fix in #161
