### ISSUE TITLE
problem: hunter queue does not have a max limit in addition to 5s wait

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/bearded-avenger#179]
solution: add max queue limit to wait

**Comment by JustinAzoff** [comment]
this comment is not right "num of records before we start throttling a token"

It's really the number of records before the queue is flushed. I'd also consider making it 500, which is the same size smrt uses.

**Comment by JustinAzoff** [comment]
oh nevermind, i see what got changed to what.  I think
CREATE_QUEUE_LIMIT needs to go back more towards 10.  Otherwise with the current values it can still do CREATE_QUEUE_LIMIT/CREATE_QUEUE_FLUSH commits per second, which equals 50.

**Comment by JustinAzoff** [comment]
can tell from my perf graphs that disk IO is up too since this param was changed

**Comment by wesyoung** [comment]
... testing with CIF_STORE_TIMEOUT=300

**Comment by JustinAzoff** [comment]
That seems to have worked better

**Comment by wesyoung** [comment]
kk. will tweak as necessary.
