### ISSUE TITLE
problem: SQLite EasyButton failing on fresh Ubuntu Server 14.04LTS - 

### ISSUE THREAD

**Issue by cjhc** [csirtgadgets/bearded-avenger#185]
In base Ubuntu Server 14.04LTS build, some Python dependencies don't get met seemlessly using "easybutton" (https://github.com/csirtgadgets/bearded-avenger/wiki/Ubuntu14LTS). Before running the SQLite easybutton.sh script, missing dev libraries should be added.

The failed task generates:

> Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?  

Missing development libraries, resolved via:
sudo apt-get install libxml2-dev libxslt1-dev python-lxml

```
PLAY RECAP *********************************************************************
localhost                  : ok=66   changed=54   unreachable=0    failed=0 
```

**Comment by wesyoung** [comment]
fixed in #193, next time feel free to send a PR too, we very rarely turn those away... (give you credit for the fix, etc ;))

ty!
