### ISSUE TITLE
problem: elasticsearch bootstrap doesn't deploy properly

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/bearded-avenger#197]

**Comment by cjhc** [comment]
TASK [elasticsearch : pull recent docker image] ********************************
task path: /home/cif/bearded-avenger/deployment/ubuntu14/roles/elasticsearch/tasks/main.yml:39
fatal: [localhost]: FAILED! => {"ansible_job_id": "672457020417.32283", "changed": true, "cmd": ["docker", "pull", "elasticsearch:2"], "delta": "0:00:00.010670", "end": "2016-12-19 16:15:45.629909", "failed": true, "finished": 1, "rc": 1, "start": "2016-12-19 16:15:45.619239", "stderr": "Cannot connect to the Docker daemon. Is the docker daemon running on this host?", "stdout": "Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon. Is the docker daemon running on this host?). Using system default: https://index.docker.io/v1/", "stdout_lines": ["Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon. Is the docker daemon running on this host?). Using system default: https://index.docker.io/v1/"], "warnings": []}

**Comment by wesyoung** [comment]
@cjhc that's a different issue than what i was fixing in the fix/es branch, what release are you testing with and what OS/ver?

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/bearded-avenger/pull/201
