### ISSUE TITLE
problem: update_last_activity happens too often

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/bearded-avenger#199]
https://github.com/csirtgadgets/bearded-avenger/blob/master/cif/store/__init__.py#L156

need to treat it like we do with the token cache and do it within store so it off-loads router.

**Comment by JustinAzoff** [comment]
also 

https://github.com/csirtgadgets/bearded-avenger/blob/master/cif/constants.py#L39

**Comment by tk-hendrik** [comment]
Hopefully like that - please feel free to spent a detail look into and change if I misunderstood the wanted logic.
