### ISSUE TITLE
problem: httpd re-encodes results too many times

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/bearded-avenger#200]
use the --no-decode flag to the zmq client to get teh string, then append as the result rather than re-encoding it

https://github.com/csirtgadgets/bearded-avenger/blob/master/cif/httpd/__init__.py#L179

**Comment by wesyoung** [comment]
justinazoff yeah... one thing go lets you do that is pretty fast is you can json encode write to the response buffer

justinazoff though in theory json.dump in python woudl let you do that

but i think json lines is a better solution anyway maybe

**Comment by JustinAzoff** [comment]
On my WiP branch:

Before: indicators limit=201000 took 7.02 seconds  
After: indicators limit=201000 took 3.62 seconds
