### ISSUE TITLE
task failure with bearded-avenger-3.0.0a14 release - TASK [elasticsearch : Add docker repo]

### ISSUE THREAD

**Issue by cjhc** [csirtgadgets/bearded-avenger#208]
Building on Ubuntu14LTS using "EasyButton - Elasticsearch" steps.

$ sudo bash bootstrap_elasticsearch.sh:
```
TASK [elasticsearch : Add docker repo] *****************************************
task path: /home/cif/bearded-avenger-3.0.0a14/deployment/ubuntu14/roles/elasticsearch/tasks/main.yml:6
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: , E:Some index files failed to download. They have been ignored, or old ones used instead.
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_78GHED/ansible_module_apt_repository.py\", line 522, in <module>\n    main()\n  File \"/tmp/ansible_78GHED/ansible_module_apt_repository.py\", line 512, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 440, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: W:Failed to fetch http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu/dists/trusty/Release.gpg  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)\n, W:Failed to fetch http://ppa.launchpad.net/maxmind/ppa/ubuntu/dists/trusty/Release.gpg  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)\n, W:Failed to fetch http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu/dists/trusty/main/i18n/Translation-en_CA  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)\n, W:Failed to fetch http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu/dists/trusty/main/i18n/Translation-en  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)\n, W:Failed to fetch http://ppa.launchpad.net/maxmind/ppa/ubuntu/dists/trusty/main/i18n/Translation-en_CA  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)\n, W:Failed to fetch http://ppa.launchpad.net/maxmind/ppa/ubuntu/dists/trusty/main/i18n/Translation-en  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)\n, W:Failed to fetch http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu/dists/trusty/main/binary-amd64/Packages  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)\n, W:Failed to fetch http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu/dists/trusty/main/binary-i386/Packages  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)\n, W:Failed to fetch http://ppa.launchpad.net/maxmind/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)\n, W:Failed to fetch http://ppa.launchpad.net/maxmind/ppa/ubuntu/dists/trusty/main/binary-i386/Packages  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)\n, W:Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages  \n, W:Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-i386/Packages  \n, E:Some index files failed to download. They have been ignored, or old ones used instead.\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by cjhc** [comment]
Re-ran the ansible playbook for ES:

beardedavenger-ES:~/bearded-avenger-3.0.0a14/deployment/ubuntu14⟫ sudo ansible-playbook -i "localhost," -c local elasticsearch.yml -vv

```
TASK [elasticsearch : Update apt cache if needed.] *****************************
task path: /home/cif/bearded-avenger-3.0.0a14/deployment/ubuntu14/roles/elasticsearch/tasks/main.yml:9
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Could not fetch updated apt files"}
```

Some of the apt repos added are failing, no proxy or firewall filtering in the path:

```
W: Failed to fetch http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu/dists/trusty/Release.gpg  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)

W: Failed to fetch http://ppa.launchpad.net/maxmind/ppa/ubuntu/dists/trusty/Release.gpg  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)

W: Failed to fetch http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu/dists/trusty/main/i18n/Translation-en_CA  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)

W: Failed to fetch http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu/dists/trusty/main/i18n/Translation-en  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)

W: Failed to fetch http://ppa.launchpad.net/maxmind/ppa/ubuntu/dists/trusty/main/i18n/Translation-en_CA  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)

W: Failed to fetch http://ppa.launchpad.net/maxmind/ppa/ubuntu/dists/trusty/main/i18n/Translation-en  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)

W: Failed to fetch http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu/dists/trusty/main/binary-amd64/Packages  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)

W: Failed to fetch http://ppa.launchpad.net/fkrull/deadsnakes-python2.7/ubuntu/dists/trusty/main/binary-i386/Packages  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)

W: Failed to fetch http://ppa.launchpad.net/maxmind/ppa/ubuntu/dists/trusty/main/binary-amd64/Packages  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)

W: Failed to fetch http://ppa.launchpad.net/maxmind/ppa/ubuntu/dists/trusty/main/binary-i386/Packages  Cannot initiate the connection to ppa.launchpad.net:80 (91.189.95.83). - connect (101: Network is unreachable)

W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-amd64/Packages  

W: Failed to fetch https://apt.dockerproject.org/repo/dists/ubuntu-trusty/main/binary-i386/Packages  

E: Some index files failed to download. They have been ignored, or old ones used instead.
```
bootstrap_elasticsearch.sh appears to be breaking DNS part way through the process, which results in failures.

After the "Add docker repo" failure above:
```
cif@beardedavenger-ES:~$ dig +short ca.archive.ubuntu.com
cif@beardedavenger-ES:~$ 
```
After bringing down, up, and renewing DHCP lease on intf, then restarting BIND:
```
cif@beardedavenger-ES:~$ dig +short ca.archive.ubuntu.com
91.189.88.162
91.189.88.152
91.189.88.149
91.189.88.161
```

If ``&& dhclient eth0`` is appdended to "bearded-avenger-3.0.0a14/deployment/ubuntu14/roles/ubuntu14/tasks/bind.yml" if appears to resolve the broken DNS:
```
$ cat bearded-avenger-3.0.0a14/deployment/ubuntu14/roles/ubuntu14/tasks/bind.yml 
---
- name: Install bind9
  apt: pkg=bind9 state=installed update_cache=true cache_valid_time=86400
  notify: restart bind9

- name: "Setting named.conf.options"
  copy: src=bind_named.conf.options dest=/etc/bind/named.conf.options

- name: "Setting named.conf.local"
  copy: src=bind_named.conf.local dest=/etc/bind/named.conf.local

- name: "Setting dhclient.conf"
  copy: src=bind_dhclient.conf dest=/etc/dhcp/dhclient.conf

- name: "Setting /etc/resolvconf/resolv.conf.d/base"
  copy: src=bind_base dest=/etc/resolvconf/resolv.conf.d/base

- name: "Restart networking"
  command: bash -c "ifdown eth0 && ifup eth0"
```

With that change, the bootstrap completes successfully.

**Comment by wesyoung** [comment]
are you testing this on bare metal? or a vm of sorts... i was using virtualbox+vagrant to test and didn't run into this issue (using a private nat, leased address)? and i'm assuming you're using a dchp address, the problem being if we add that, what would it do for statically addressed boxes? which will be typical in most deployments... (i would think?)

**Comment by cjhc** [comment]
@wesyoung DHCP addressed VM within VirtualBox. I don't know why the interface isn't coming back up and needs a dhclient renewal, its odd. My (re)deployment will be on a VM on an ESXi hypervisor, but statically addressed.

So yes, adding that would likely be a problem... you're right. In my scenario, it is losing networking and failing in an non-graceful way.

**Comment by wesyoung** [comment]
are you starting out with 14.04.4 or 14.04.5 ?

**Comment by cjhc** [comment]
Running a test build on Ubuntu 14.04.4 LTS (GNU/Linux 4.2.0-27-generic x86_64) using 3.0.0a14:

```
cif@beardedavenger-ES:~⟫ wget https://github.com/csirtgadgets/bearded-avenger/archive/3.0.0a14.tar.gz
cif@beardedavenger-ES:~⟫ tar zxvf 3.0.0a14.tar.gz
cif@beardedavenger-ES:~⟫ cd bearded-avenger-3.0.0a14/deployment/ubuntu14/
cif@beardedavenger-ES:~/bearded-avenger-3.0.0a14/deployment/ubuntu14⟫ sudo bash bootstrap_elasticsearch.sh
```

Failure:

> TASK [ubuntu14 : install nginx] ************************************************
> task path: /home/cif/bearded-avenger-3.0.0a14/deployment/ubuntu14/roles/ubuntu14/tasks/nginx.yml:2
> fatal: [localhost]: FAILED! => {"cache_update_time": 0, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'nginx'' failed: E: Failed to fetch http://ca.archive.ubuntu.com/ubuntu/pool/main/f/fonts-dejavu/fonts-dejavu-core_2.34-1ubuntu1_all.deb  Could not resolve 'ca.archive.ubuntu.com'\n\nE: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/f/fontconfig/fontconfig-config_2.11.0-0ubuntu4.2_all.deb

**Comment by cjhc** [comment]
And with Ubuntu 14.04.5 LTS (GNU/Linux 4.2.0-42-generic x86_64) (both this test and above without the dodgy dhcp "fix"):

Failure:
> TASK [ubuntu14 : install nginx] ************************************************
> task path: /home/cif/bearded-avenger-3.0.0a14/deployment/ubuntu14/roles/ubuntu14/tasks/nginx.yml:2
> fatal: [localhost]: FAILED! => {"cache_update_time": 0, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'nginx'' failed: E: Failed to fetch http://ca.archive.ubuntu.com/ubuntu/pool/main/f/fonts-dejavu/fonts-dejavu-core_2.34-1ubuntu1_all.deb

**Comment by cjhc** [comment]
And now on Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-57-generic x86_64) with the ugly dhclient fix:

SUCCESS

> PLAY RECAP *********************************************************************
> localhost                  : ok=90   changed=64   unreachable=0    failed=0   
> 
> testing connectivity
> 2017-01-03 16:55:43,605 - INFO - cifsdk.client.client[110][MainThread] - running ping
> roundtrip: 0.0181679725647 ms
> roundtrip: 0.0105409622192 ms
> roundtrip: 0.0093789100647 ms
> roundtrip: 0.0184948444366 ms
> testing connectivity
> 2017-01-03 16:55:48,099 - INFO - cifsdk.client.client[110][MainThread] - running ping
> roundtrip: 0.0114359855652 ms
> roundtrip: 0.0100190639496 ms
> roundtrip: 0.00905680656433 ms
> roundtrip: 0.00936198234558 ms
> testing query
> 2017-01-03 16:55:52,514 - INFO - cifsdk.client.client[153][MainThread] - searching for example.com
> +-----+----------+------------+-------+-----------+-------+----+-----+----------+------------+-------------+------+-------+----------+
> | tlp | lasttime | reporttime | itype | indicator | count | cc | asn | asn_desc | confidence | description | tags | rdata | provider |
> +-----+----------+------------+-------+-----------+-------+----+-----+----------+------------+-------------+------+-------+----------+
> +-----+----------+------------+-------+-----------+-------+----+-----+----------+------------+-------------+------+-------+----------+
> waiting...
> testing query
> 2017-01-03 16:55:58,336 - INFO - cifsdk.client.client[153][MainThread] - searching for example.com
> +-------+----------------------------+----------------------------+-------+-------------+-------+----+-----+----------+------------+-------------+--------+-------+----------+
> |  tlp  |          lasttime          |         reporttime         | itype |  indicator  | count | cc | asn | asn_desc | confidence | description |  tags  | rdata | provider |
> +-------+----------------------------+----------------------------+-------+-------------+-------+----+-----+----------+------------+-------------+--------+-------+----------+
> | amber | 2017-01-04T00:55:52.54000Z | 2017-01-04T00:55:52.54000Z |  fqdn | example.com |       |    |     |          |     10     |             | search |       | admin    |
> +-------+----------------------------+----------------------------+-------+-------------+-------+----+-----+----------+------------+-------------+--------+-------+----------+
> waiting...
> 2017-01-03 16:56:03,762 - INFO - cifsdk.client.client[136][MainThread] - searching for ipv4
> +-----+----------+------------+-------+-----------+-------+----+-----+----------+------------+-------------+------+-------+----------+
> | tlp | lasttime | reporttime | itype | indicator | count | cc | asn | asn_desc | confidence | description | tags | rdata | provider |
> +-----+----------+------------+-------+-----------+-------+----+-----+----------+------------+-------------+------+-------+----------+
> +-----+----------+------------+-------+-----------+-------+----+-----+----------+------------+-------------+------+-------+----------+
> 2017-01-03 16:56:04,145 - INFO - cifsdk.client.client[153][MainThread] - searching for 93.184.216.34
> +-----+----------+------------+-------+-----------+-------+----+-----+----------+------------+-------------+------+-------+----------+
> | tlp | lasttime | reporttime | itype | indicator | count | cc | asn | asn_desc | confidence | description | tags | rdata | provider |
> +-----+----------+------------+-------+-----------+-------+----+-----+----------+------------+-------------+------+-------+----------+
> +-----+----------+------------+-------+-----------+-------+----+-----+----------+------------+-------------+------+-------+----------+
> waiting...
> 2017-01-03 16:56:09,713 - INFO - cifsdk.client.client[153][MainThread] - searching for 93.184.216.34
> +-------+----------------------------+----------------------------+-------+---------------+-------+----+-----+----------+------------+-------------+--------+-------+----------+
> |  tlp  |          lasttime          |         reporttime         | itype |   indicator   | count | cc | asn | asn_desc | confidence | description |  tags  | rdata | provider |
> +-------+----------------------------+----------------------------+-------+---------------+-------+----+-----+----------+------------+-------------+--------+-------+----------+
> | amber | 2017-01-04T00:56:04.17000Z | 2017-01-04T00:56:04.17000Z |  ipv4 | 93.184.216.34 |       |    |     |          |     10     |             | search |       | admin    |
> +-------+----------------------------+----------------------------+-------+---------------+-------+----+-----+----------+------------+-------------+--------+-------+----------+

Subsequent steps all completed successfully.

This may be a problem unique to my context, so if that's your conclusion then feel free to close the issue. Otherwise, I'll keep testing.

**Comment by wesyoung** [comment]
if it's a problem for you, it's going to be a problem for others too. my guess is we need some sort of ansible if/then/else that detects if you're using dhclient and applies it accordingly...
