### ISSUE TITLE
CIFv2 vs CIFv3

### ISSUE THREAD

**Issue by jet1276** [csirtgadgets/bearded-avenger#237]
Hi team,

Which version of CIF is recommended for stable use?

**Comment by josarsepi** [comment]
https://github.com/csirtgadgets/massive-octo-spice/issues/465
https://www.elastic.co/support/eol

EOL for the version of elastic being used in CIFv2 was last week.  I recommend using CIFv3 if you are doing more then a test.

Additional note, PIP has a bug that breaks the easybutton in CIFv3 right now:
https://bugs.launchpad.net/ubuntu/+source/python-pip/+bug/1658844

Hopefully pip will fix this soon.

**Comment by kingprakatheesh** [comment]
Hi i want to integrate Kibana, Elasticsearch with CIF v3. Can anyone suggest how to proceed ? Thank you

**Comment by wesyoung** [comment]
@jet1276 i agree, if you're just getting into this i'd start with v3. it's getting more and more stable every day and we're getting close to start releasing betas (need to do some work on elasticsearch bits, but everything else is getting stable).

**Comment by wesyoung** [comment]
@kingprakatheesh checkout out the bootstrap quickstart for elasticsearch:

https://github.com/csirtgadgets/bearded-avenger/wiki/Ubuntu14LTS#easybutton---elasticsearch

as far as kibana; i've not messed with it yet, but i think others on the mailing list have:

https://groups.google.com/forum/#!forum/ci-framework

i think there are still a few quirks to be worked out in terms of kibana and elasticsearch performance, but we happily accept PRs as we're working through these issues..
