### ISSUE TITLE
problem: sqlite indicators_ipv4 index is a little slow; and should use hex?

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/bearded-avenger#265]
use blocklist.de to test with.

**Comment by JustinAzoff** [comment]
I think no encoding + change column data type to BINARY is what we want.

    import socket
    from sqlalchemy import Table, Column, Integer, String, MetaData, ForeignKey, BINARY, create_engine
    metadata = MetaData()
    
    engine = create_engine('sqlite:///foo.db', echo=True)
    
    ips = Table('ips', metadata,
      Column('id', Integer, primary_key=True),
      Column('ip', BINARY, nullable=False)
    )
    
    conn = engine.connect()
    metadata.create_all(engine)
    
    def i(ip):
        value = socket.inet_pton(socket.AF_INET, ip)
        ins = ips.insert().values(ip=value)
        conn.execute(ins)
    
    i("1.2.3.4")
    i("87.69.83.33")

Results in:

    $ sqlite3 foo.db .dump
    PRAGMA foreign_keys=OFF;
    BEGIN TRANSACTION;
    CREATE TABLE ips (
    	id INTEGER NOT NULL,
    	ip BINARY NOT NULL,
    	PRIMARY KEY (id)
    );
    INSERT INTO "ips" VALUES(1,X'01020304');
    INSERT INTO "ips" VALUES(2,X'57455321');
    COMMIT;
    $ sqlite3 foo.db 'select * from ips';
    1|
    2|WES!
    $

**Comment by wesyoung** [comment]
https://github.com/zzzeek/sqlalchemy/blob/master/lib/sqlalchemy/sql/sqltypes.py#L852
