### ISSUE TITLE
TASK [bearded-avenger : run tests] Fails on Ubuntu 16 TLS

### ISSUE THREAD

**Issue by schizophrenchen** [csirtgadgets/bearded-avenger#266]
Hi all,
i tried to install release 3.0.0a16 (https://github.com/csirtgadgets/bearded-avenger/archive/3.0.0a16.tar.gz) on Ubuntu. Here is my output from /etc/lsb-release:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

I run into errors during "Test" phase of "easybutton.sh". I strictly followed the Ubuntu 16 install instructions beside that i did run as root directly, rather than sudo.

Full error message is:

TASK [bearded-avenger : run tests] *********************************************
task path: /opt/arcsight/installers/bearded-avenger-3.0.0a16/deployment/roles/bearded-avenger/tasks/dist.yml:24
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["python", "setup.py", "test"], "delta": "0:00:14.097891", "end": "2017-03-02 11:54:21.365704", "failed": true, "rc": 1, "start": "2017-03-02 11:54:07.267813", "stderr": "Traceback (most recent call last):
  File \"setup.py\", line 27, in <module>
    raise RuntimeError('tests failed')
RuntimeError: tests failed", "stdout": "============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-2.8.7, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python
cachedir: .cache
rootdir: /tmp/cif-3.0.0a16, inifile: 
plugins: cov-2.4.0
collecting ... collected 27 items

test/test_gatherer_asn.py::test_gatherer_asn PASSED
test/test_gatherer_asn.py::test_gatherer_asn_fast SKIPPED
test/test_gatherer_geo.py::test_gatherer_geo PASSED
test/test_gatherer_peer.py::test_gatherer_peer FAILED
test/test_httpd.py::test_httpd_help PASSED
test/test_httpd.py::test_httpd_ping PASSED
test/test_httpd.py::test_httpd_search PASSED
test/test_httpd.py::test_httpd_indicators PASSED
test/test_httpd.py::test_httpd_feed PASSED
test/test_httpd.py::test_httpd_tokens PASSED
test/test_hunter.py::test_hunter PASSED
test/test_peers.py::test_gatherer_peers FAILED
test/test_router.py::test_router_basics PASSED
test/test_store.py::test_store_dummy PASSED
test/zadvanced/test_hunter.py::test_zadvanced_hunter_start SKIPPED
test/zelasticsearch/test_store_elasticsearch_indicators.py::test_store_elasticsearch_indicators SKIPPED
test/zelasticsearch/test_store_elasticsearch_indicators.py::test_store_elasticsearch_indicators_ipv6 SKIPPED
test/zelasticsearch/test_store_elasticsearch_tokens.py::test_store_elasticsearch_tokens SKIPPED
test/zelasticsearch/test_store_elasticsearch_tokens.py::test_store_elasticsearch_tokens_advanced SKIPPED
test/zelasticsearch/test_store_elasticsearch_tokens.py::test_store_elasticsearch_tokens_groups SKIPPED
test/zelasticsearch/test_store_elasticsearch_tokens.py::test_store_elasticsearch_tokens_groups2 SKIPPED
test/zelasticsearch/test_store_elasticsearch_tokens.py::test_store_elasticsearch_tokens_groups3 SKIPPED
test/zsqlite/test_store_sqlite_indicators.py::test_store_sqlite_indicators PASSED
test/zsqlite/test_store_sqlite_tokens.py::test_store_sqlite_tokens PASSED
test/zsqlite/test_store_sqlite_tokens.py::test_store_sqlite_tokens_groups PASSED
test/zsqlite/test_store_sqlite_tokens.py::test_store_sqlite_tokens_groups2 PASSED
test/zsqlite/test_store_sqlite_tokens.py::test_store_sqlite_tokens_groups3 PASSED

---------- coverage: platform linux2, python 2.7.12-final-0 ----------
Name                                    Stmts   Miss Branch BrPart  Cover
-------------------------------------------------------------------------
cif/__init__.py                             3      0      0      0   100%
cif/gatherer/__init__.py                   78     54     14      1    27%
cif/gatherer/asn.py                        63     23     22      7    55%
cif/gatherer/peers.py                      40      4     16      6    82%
cif/httpd/__init__.py                      58     17      4      0    73%
cif/httpd/common.py                        49     28     21      0    33%
cif/httpd/views/__init__.py                 0      0      0      0   100%
cif/httpd/views/confidence.py               6      1      0      0    83%
cif/httpd/views/help.py                     5      0      0      0   100%
cif/httpd/views/indicators.py              66     43     32      4    30%
cif/httpd/views/ping.py                    25      9      8      2    55%
cif/httpd/views/tokens.py                  64     43     20      1    29%
cif/hunter/__init__.py                     91     58     34      2    28%
cif/store/__init__.py                     304    183    110     15    34%
cif/store/indicator_plugin.py              28     12     14      0    48%
cif/store/sqlite/__init__.py               49      4      8      3    84%
cif/store/sqlite/indicator.py             314     52    116     28    80%
cif/store/sqlite/ip.py                     31      5      4      1    83%
cif/store/sqlite/token.py                 114     18     38     11    81%
cif/store/token_plugin.py                  53     12     14      4    70%
cif/store/zelasticsearch/__init__.py       38     38      8      0     0%
cif/store/zelasticsearch/indicator.py     240    240     80      0     0%
cif/store/zelasticsearch/token.py          91     91     40      0     0%
cif/utils/__init__.py                      25      8      8      0    58%
cif/utils/asn_client.py                    66     52     30      0    15%
-------------------------------------------------------------------------
TOTAL                                    1901    995    641     85    43%

=================================== FAILURES ===================================
______________________________ test_gatherer_peer ______________________________

    def test_gatherer_peer():
        a = Peer()
    
        def _resolve(i):
            return data
    
        a._resolve_ns = _resolve
        x = a.process(Indicator(indicator='216.90.108.0'))
    
        pprint(x)
    
>       assert x.peers[0]['asn'] == '23352'
E       assert '174' == '23352'
E         - 174
E         + 23352

test/test_gatherer_peer.py:23: AssertionError
----------------------------- Captured stdout call -----------------------------
{
    \"indicator\": \"216.90.108.0\",
    \"itype\": \"ipv4\",
    \"peers\": [
        {
            \"asn\": \"174\",
            \"cc\": \"US\",
            \"prefix\": \"216.90.108.0/24\",
            \"rir\": \"arin |\"
        },
        {
            \"asn\": \"2381\",
            \"cc\": \"US\",
            \"prefix\": \"216.90.108.0/24\",
            \"rir\": \"arin |\"
        }
    ]
}
_____________________________ test_gatherer_peers ______________________________

    def test_gatherer_peers():
        p = Peer()
    
        def _resolve(i):
            return data
    
        p._resolve_ns = _resolve
        x = p.process(Indicator(indicator='216.90.108.0'))
    
        mypeers = set()
        for pp in x.peers:
            mypeers.add(pp['asn'])
    
>       assert '23352' in mypeers
E       assert '23352' in set(['174', '2381'])

test/test_peers.py:27: AssertionError
=============== 2 failed, 16 passed, 9 skipped in 13.49 seconds ================", "stdout_lines": ["============================= test session starts ==============================", "platform linux2 -- Python 2.7.12, pytest-2.8.7, py-1.4.31, pluggy-0.3.1 -- /usr/bin/python", "cachedir: .cache", "rootdir: /tmp/cif-3.0.0a16, inifile: ", "plugins: cov-2.4.0", "collecting ... collected 27 items", "", "test/test_gatherer_asn.py::test_gatherer_asn PASSED", "test/test_gatherer_asn.py::test_gatherer_asn_fast SKIPPED", "test/test_gatherer_geo.py::test_gatherer_geo PASSED", "test/test_gatherer_peer.py::test_gatherer_peer FAILED", "test/test_httpd.py::test_httpd_help PASSED", "test/test_httpd.py::test_httpd_ping PASSED", "test/test_httpd.py::test_httpd_search PASSED", "test/test_httpd.py::test_httpd_indicators PASSED", "test/test_httpd.py::test_httpd_feed PASSED", "test/test_httpd.py::test_httpd_tokens PASSED", "test/test_hunter.py::test_hunter PASSED", "test/test_peers.py::test_gatherer_peers FAILED", "test/test_router.py::test_router_basics PASSED", "test/test_store.py::test_store_dummy PASSED", "test/zadvanced/test_hunter.py::test_zadvanced_hunter_start SKIPPED", "test/zelasticsearch/test_store_elasticsearch_indicators.py::test_store_elasticsearch_indicators SKIPPED", "test/zelasticsearch/test_store_elasticsearch_indicators.py::test_store_elasticsearch_indicators_ipv6 SKIPPED", "test/zelasticsearch/test_store_elasticsearch_tokens.py::test_store_elasticsearch_tokens SKIPPED", "test/zelasticsearch/test_store_elasticsearch_tokens.py::test_store_elasticsearch_tokens_advanced SKIPPED", "test/zelasticsearch/test_store_elasticsearch_tokens.py::test_store_elasticsearch_tokens_groups SKIPPED", "test/zelasticsearch/test_store_elasticsearch_tokens.py::test_store_elasticsearch_tokens_groups2 SKIPPED", "test/zelasticsearch/test_store_elasticsearch_tokens.py::test_store_elasticsearch_tokens_groups3 SKIPPED", "test/zsqlite/test_store_sqlite_indicators.py::test_store_sqlite_indicators PASSED", "test/zsqlite/test_store_sqlite_tokens.py::test_store_sqlite_tokens PASSED", "test/zsqlite/test_store_sqlite_tokens.py::test_store_sqlite_tokens_groups PASSED", "test/zsqlite/test_store_sqlite_tokens.py::test_store_sqlite_tokens_groups2 PASSED", "test/zsqlite/test_store_sqlite_tokens.py::test_store_sqlite_tokens_groups3 PASSED", "", "---------- coverage: platform linux2, python 2.7.12-final-0 ----------", "Name                                    Stmts   Miss Branch BrPart  Cover", "-------------------------------------------------------------------------", "cif/__init__.py                             3      0      0      0   100%", "cif/gatherer/__init__.py                   78     54     14      1    27%", "cif/gatherer/asn.py                        63     23     22      7    55%", "cif/gatherer/peers.py                      40      4     16      6    82%", "cif/httpd/__init__.py                      58     17      4      0    73%", "cif/httpd/common.py                        49     28     21      0    33%", "cif/httpd/views/__init__.py                 0      0      0      0   100%", "cif/httpd/views/confidence.py               6      1      0      0    83%", "cif/httpd/views/help.py                     5      0      0      0   100%", "cif/httpd/views/indicators.py              66     43     32      4    30%", "cif/httpd/views/ping.py                    25      9      8      2    55%", "cif/httpd/views/tokens.py                  64     43     20      1    29%", "cif/hunter/__init__.py                     91     58     34      2    28%", "cif/store/__init__.py                     304    183    110     15    34%", "cif/store/indicator_plugin.py              28     12     14      0    48%", "cif/store/sqlite/__init__.py               49      4      8      3    84%", "cif/store/sqlite/indicator.py             314     52    116     28    80%", "cif/store/sqlite/ip.py                     31      5      4      1    83%", "cif/store/sqlite/token.py                 114     18     38     11    81%", "cif/store/token_plugin.py                  53     12     14      4    70%", "cif/store/zelasticsearch/__init__.py       38     38      8      0     0%", "cif/store/zelasticsearch/indicator.py     240    240     80      0     0%", "cif/store/zelasticsearch/token.py          91     91     40      0     0%", "cif/utils/__init__.py                      25      8      8      0    58%", "cif/utils/asn_client.py                    66     52     30      0    15%", "-------------------------------------------------------------------------", "TOTAL                                    1901    995    641     85    43%", "", "", "=================================== FAILURES ===================================", "______________________________ test_gatherer_peer ______________________________", "", "    def test_gatherer_peer():", "        a = Peer()", "    ", "        def _resolve(i):", "            return data", "    ", "        a._resolve_ns = _resolve", "        x = a.process(Indicator(indicator='216.90.108.0'))", "    ", "        pprint(x)", "    ", ">       assert x.peers[0]['asn'] == '23352'", "E       assert '174' == '23352'", "E         - 174", "E         + 23352", "", "test/test_gatherer_peer.py:23: AssertionError", "----------------------------- Captured stdout call -----------------------------", "{", "    \"indicator\": \"216.90.108.0\",", "    \"itype\": \"ipv4\",", "    \"peers\": [", "        {", "            \"asn\": \"174\",", "            \"cc\": \"US\",", "            \"prefix\": \"216.90.108.0/24\",", "            \"rir\": \"arin |\"", "        },", "        {", "            \"asn\": \"2381\",", "            \"cc\": \"US\",", "            \"prefix\": \"216.90.108.0/24\",", "            \"rir\": \"arin |\"", "        }", "    ]", "}", "_____________________________ test_gatherer_peers ______________________________", "", "    def test_gatherer_peers():", "        p = Peer()", "    ", "        def _resolve(i):", "            return data", "    ", "        p._resolve_ns = _resolve", "        x = p.process(Indicator(indicator='216.90.108.0'))", "    ", "        mypeers = set()", "        for pp in x.peers:", "            mypeers.add(pp['asn'])", "    ", ">       assert '23352' in mypeers", "E       assert '23352' in set(['174', '2381'])", "", "test/test_peers.py:27: AssertionError", "=============== 2 failed, 16 passed, 9 skipped in 13.49 seconds ================"], "warnings": []}

RUNNING HANDLER [ubuntu16 : restart bind9] *************************************

RUNNING HANDLER [ubuntu16 : reload systemd] ************************************
        to retry, use: --limit @/opt/arcsight/installers/bearded-avenger-3.0.0a16/deployment/ubuntu16/localhost.retry

PLAY RECAP *********************************************************************
localhost                  : ok=39   changed=33   unreachable=0    failed=1

Can anybody help with this?
I'd also happy to run another version which is stable on Ubuntu or CentOS. CentOS 7.2 BTW shows same error.

Thanks,
Markus

P.S.: my Ubuntu is a standard install

**Comment by wesyoung** [comment]
hold tight; currently working on an a17 release that should fix this (some things changed wrt that test and the upstream that we're using to find peer information). should have it done any day now.. ❌ 
(will update this ticket when it's released.. network based tests SHOULD NOT break install's, that was dumb and fault.)

**Comment by schizophrenchen** [comment]
Thats great info. Thanks. I will stand by for your update.

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/bearded-avenger/releases/tag/3.0.0a17

try that; let me know.. (closing for now; re-open with new issue).

ty for the feedback!

**Comment by schizophrenchen** [comment]
Hi there,
seems that new version has issue with working directory. stops in script easybutton.sh line 50 with "ubuntu16 no such file or directory". Runs well if i use the relative path starting from unzip dir.
Run installation from /opt/bearded-avenger/ and changed path in line 50 to "./deployment/ubuntu16" which works.

Minor fix required or do i miss a thing?

Markus

**Comment by wesyoung** [comment]
no; the doc was a little off [just updated]. should have read..

```
$ cd cif-3.X.X
$ cd deployment
$ sudo bash easybutton.sh
...
```

**Comment by schizophrenchen** [comment]
very sorry. just recognized it. ignore my previous comment

**Comment by wesyoung** [comment]
no; it was wrong, i just edited it before i sent you the msg. it was my fault :)

**Comment by schizophrenchen** [comment]
so i can now confirm. a17 on ubuntu 16LTS worked great for me.

**Comment by wesyoung** [comment]
good deal. spent a good chunk of cycles on interactive performance, so be interested after a few weeks how things are working out for you... ty for the awesome feedback!
