### ISSUE TITLE
problem: centos73 does not have python-pip available by default (python2|3-pip)

### ISSUE THREAD

**Issue by schizophrenchen** [csirtgadgets/bearded-avenger#270]
Hi Wes,
There might be an issue with system preparations installing packages through bootstrap.sh.

On my CentOS, there was no python-pip available, even not with epel-release installed.
IMHO, it should be python2-pip or python34-pip.

I also believe to remember, that epel-release installation was not executed from bootstrap.sh.
Is that supposed to come from any ansible playbook?

Have not checked on Ubuntu, but might be trough there as well...

Cheers,
Markts

**Comment by wesyoung** [comment]
what version of CentOS are you running?

**Comment by schizophrenchen** [comment]
Hi Wes,
i am running on 7.3. The problem with python-pip was not, that it was not recognized (in whatever place), it was not available. The package naming was different when checking with YUM.
The following is executed AFTER manual install of epel-release and python cip packages:

[root@arcsight-cif-03 ~]# yum list installed | grep -i python | grep -i pip
python2-pip.noarch                     8.1.2-5.el7                     @epel
python34-pip.noarch                    8.1.2-5.el7                     @epel

So to me,there is no package available, what is also shown by the following command:
[root@arcsight-cif-03 ~]# yum list available | grep -i python | grep -i pip
python-apipkg.noarch                      1.2-7.el7                      epel
python-django-pipeline.noarch             1.3.24-1.el7                   epel

Thus, i installed python34-pip. 

HTH,
MM

**Comment by wesyoung** [comment]
understood; i bet python34-pip will mess things up unless you're running python3 by default (which should work OK, i dev against that and then backport fixes for py2 where we test in prod).

i haven't tested this on 7.3 yet, but am also wondering if the vagrant image i'm using (based on 7.2) has an EPEL repo in it that makes python-pip available to my testing by default ?

i'll leave this open for now and make sure we test it in the next round. see if python2-pip is available in my tree and set that as the default if it is. if it's not, may need to do some testing between 72 and 73 to see what the differences are...

does that make sense?

**Comment by wesyoung** [comment]
errrmmm

```
$ yum search python-pip
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.atlanticmetro.net
 * epel: mirror.us.leaseweb.net
 * extras: centos.gbeservers.com
 * updates: mirror.tzulo.com
Warning: No matches found for: python-pip
No matches found
```

```
]$ yum search python2-pip
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.atlanticmetro.net
 * epel: mirror.us.leaseweb.net
 * extras: centos.gbeservers.com
 * updates: mirror.tzulo.com
============================================================================= N/S matched: python2-pip =============================================================================
python2-pip.noarch : A tool for installing and managing Python 2 packages
```

i'll have to debug a bit to see what was going on and why it worked for me; cause you're obviously right :)

**Comment by wesyoung** [comment]
ok, after re-reading what you wrote and what i wrote (and the code.. it's been a busy week), i think the vagrant box image i'm using to test [obviously] had epel repo already installed. so when i did a yum install python-pip, it auto-resolved python2-pip and installed it.

so. i added `yum -y install epel-release` to the bootstrap.sh script to make sure it's in there for everyone since the playbooks don't do this by default (you need python to run the playbooks locally, hence the bootstrap.sh requirement).

ty for this! now hopefully it works in 7.3 (RHEL isn't my first distro of choice, but slowly warming up to it)
