### ISSUE TITLE
problem: CIF_ES_NODES is overwritten by CIF_STORE_NODES

### ISSUE THREAD

**Issue by Lefnui** [csirtgadgets/bearded-avenger#284]
Hi,

By looking at the ansible playbooks, I've figured out it is possible to use Elasticsearch as store by setting ANSIBLE_CIF_ES=1, but this will install 
I haven't found out how to install cif and using an existing Elasticsearch cluster as data store

Is this supported/planned to be supported?

**Comment by wesyoung** [comment]
yes, and it will def be easier to configure for, just haven't had the cycles to get that far yet (getting close though). the elasticsearch client side stuff is installed by default, so it's really just about adapting your own local playbook to do just about everything with the exception of

off the top of my head (and you'd have to test this), looking at:

https://github.com/csirtgadgets/bearded-avenger-deploymentkit/blob/master/ubuntu16/site.yml#L28

if you simply comment out line 39? and then set the appropriate variables (~/.cifrc or other) you see in:

https://github.com/csirtgadgets/bearded-avenger/blob/master/cif/store/zelasticsearch/__init__.py#L12

some combination of that should get you where you want to go (or closer anyway). the "set_fact" bits in the playbook denote how to configure cif-router with the correct --store flags for ES, that extra "elasticsearch" role is specifically *just* for installing ES locally only (we can probably break that into a sep variable like CIF_ES_LOCAL or something?

happy to accept a PR if you get it working (in a simple manner).

does that make sense?

(incidentally we use a remote aws cluster for our ES bits this way too, and fork out a number of cif-routers as endpoints that can be spun up and down where-as the ES cluster remains persistent, so yes on all accounts.. just been focusing on sqlite setup for ease of use, now circling around to the ES stuff as things have been stabilizing..).

**Comment by Lefnui** [comment]
OKay, just wanted to know if it was on the roadmap.

In that cas I might try to do something in that way. I was thinking about adding a "store" role to configure the store (elasticsearch or sqlite) and leave the "elasticsearch" role for the standalone install.

Does that make sense to you?

**Comment by wesyoung** [comment]
it might be overkill? given that cif-router just wants to know about those few variables(?) i think if you just set those facts in your playbook you might be ok(?). 

you can try it; see where it leads, just start with this:

https://github.com/csirtgadgets/bearded-avenger-deploymentkit

and we can bat it around a bit (use the rule; if you had only 15min to make this work, what would you do? .. then branch from that to see if it's worth all the extra configuration overhead, imo..).

in the process of moving all of that *out* of master and into it's own repo (will be more obvious in the next release).

**Comment by Lefnui** [comment]
Hi,

I was not able to get the ansible job working, so I did a regular sqlite install and then changed the value in the config.

I tried changing CIF_ES_NODES but the router still tries to connect to localhost:9200.
The problem is that nodes has None value.
When the router object is created, the nodes value (which is then passed to the store) is assigned to the value of --store-nodes, which defaults to the STORE_NODES environment variable.
When I set STORE_NODES to my nodes, it works fine.
https://github.com/csirtgadgets/bearded-avenger/blob/c717d3cbfade582b8964981877145b5445951b2e/cif/router.py#L42

The CIF_ES_NODES environment variable is not taken into account, but STORE_NODES works just fine, I dont know if that is expected behavior

**Comment by wesyoung** [comment]
ahhh i bet STORE_NODES is overwriting the other when it's booted up. awesome that it works! re-setting this as a bug to make that ... less confusing. then the ansible stuff should work.

great catch!

**Comment by Lefnui** [comment]
To get it working on Ubuntu 14.04, you have to add STORE_ES_NODES to /etc/default/cif and export CIF_STORE_NODES=$CIF_STORE_NODES to /etc/init.d/cif-router

I'll submit a PR when I'm done testing it. Should it be send in this repo or in the deployment kit repo? I didnt manage to install it with the master from deployment kit, I'm currently testing with the last release (3.0.0a17)

**Comment by wesyoung** [comment]
jah; send it to deploymentkit, i'm trying to clean that up, remove the "deployment" dir from here and do some test installs. the patch should line up OK.
