### ISSUE TITLE
cif-tokens --create causes ascii error in cif-httpd

### ISSUE THREAD

**Issue by kevinwilcox** [csirtgadgets/bearded-avenger#339]
Wes - this is the issue we'd talked about. I was wrong, it does happen on the Ubuntu installs (haven't tried a RHEL/CentOS install yet).

Reproducible on all CIFv3 Ubuntu 16.04.2 LTS installs. Command output:

cif@cif-01:~$ cif-tokens --username "new-user@cif-01" --create --admin

2017-06-26 21:48:07,740 - INFO - cifsdk.client.tokens[91][MainThread] - assuming --read token
2017-06-26 21:48:07,764 - ERROR - cifsdk.client.tokens[115][MainThread] - token create failed: The system is extremely busy at the moment, try again later.
cif@cif-01:~$ 

And in the cif-httpd log:

Jun 26 21:48:07 cif-01 cif-httpd[21507]: 2017-06-26 21:48:07,745 - ERROR - cif-httpd[54][Thread-170] - 'ascii' codec can't decode byte 0x9c in position 1: ordinal not in range(128)
Jun 26 21:48:07 cif-01 cif-httpd[21507]: 2017-06-26 21:48:07,762 - INFO - werkzeug[87][Thread-170] - 127.0.0.1 - - [26/Jun/2017 21:48:07] "POST /tokens HTTP/1.1" 503 -

**Comment by wesyoung** [comment]
ack. think it's fixed in a branch of the SDK. will try to tag a release this week that addresses this.

**Comment by wesyoung** [comment]
ok, i tagged a22 and updated the deployment kit. also added some `cif-tokens` tests to the release testing to help catch this stuff.

let me know if it fixes those issues. re-open if not...

**Comment by kevinwilcox** [comment]
That did the trick, thanks!
