### ISSUE TITLE
How to change cif store to ES after default install

### ISSUE THREAD

**Issue by nuaalwz** [csirtgadgets/bearded-avenger#347]
Hi,
I am using cifv3  and it works fine after default install, but I prefer using  elasticsearch as cif store just like cifv2 do.  The deploymentkit version I used is  3.0.0a5 and os version is Ubuntu 16.04 LTS.

I made a reference on issue [284](https://github.com/csirtgadgets/bearded-avenger/issues/284), it seems last version can only use ES in docker and I just changed CIF_ES value to "1" in ubuntu16/site.yml, it failed for image, docker key or token generate reason. I know it must be my fault but I know little about ansible , so I wanna find some ways after defalut install.

Recently I have tried to install ES on localhost and modified /etc/cif.env, change CIF_STORE_STORE value to elasticsearch, it failed with unauth error. Then I use cif-store to generate token, the cmds I have typed are below:

> cif-store --store elasticsearch --runtime-path /var/lib/cif --token-create-smrt --config-path /etc/cif/csirtg-smrt.yml  
cif-store --store elasticsearch --runtime-path /var/lib/cif --token-create-admin --config-path /home/cif/.cif.yml  
cif-store --store elasticsearch --runtime-path /var/lib/cif --token-create-hunter --config-path /etc/cif/cif-router.yml

But it raised system busy exception:

> cif@cif:~$cif
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/client.py", line 239, in main
    rv = cli.search(filters)
  File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/plugin.py", line 20, in search
    return self.indicators_search(data)
  File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/http.py", line 141, in indicators_search
    rv = self._get('/search', params=filters)
  File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/http.py", line 78, in _get
    self._check_status(resp, expect=200)
  File "/usr/local/lib/python2.7/dist-packages/cifsdk/client/http.py", line 66, in _check_status
    raise CIFBusy('system busy')
CIFBusy: system busy

I dont know where goes wrong and there are few docs about cifv3, I cant find any error logs, either.

**Comment by wesyoung** [comment]
we may have to re-visit the docker images, i wonder if someone updated something upstream-

+ did you restart cif-router `systemctl restart cif-router`
+ what do your logs say here `journalctl -f -u cif-router -n 2000`
+ did you verify your tokens were created in your ES instance? (check the `tokens` index)

ubuntu16 uses systemd now, so the logging follows that: https://www.digitalocean.com/community/tutorials/how-to-use-journalctl-to-view-and-manipulate-systemd-logs

we're starting to tag things as "beta" this month, so you should see some of the troubleshooting docs improve around that.

**Comment by nuaalwz** [comment]
Thx, wes.
Your reply reminds me of that there is a cif.token index in cifv2 ES, but I didnt find any config about token index in ansible playbooks.  Should I create such a index manually, if so, is the index mapping the same as cifv2, or there is someway that can create it automatically? 
Besides, the logs that journalctl provide about CIFBusy are below:

> Aug 14 18:47:12 cif cif-router[1717]: Process Process-2:
Aug 14 18:47:12 cif cif-router[1717]: Traceback (most recent call last):
Aug 14 18:47:12 cif cif-router[1717]:   File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Aug 14 18:47:12 cif cif-router[1717]:     self.run()
Aug 14 18:47:12 cif cif-router[1717]:   File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
Aug 14 18:47:12 cif cif-router[1717]:     self._target(*self._args, **self._kwargs)
Aug 14 18:47:12 cif cif-router[1717]:   File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0a22-py2.7.egg/cif/store/__init__.py", line 95, in start
Aug 14 18:47:12 cif cif-router[1717]:     self._load_plugin(**self.kwargs)
Aug 14 18:47:12 cif cif-router[1717]:   File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0a22-py2.7.egg/cif/store/__init__.py", line 92, in _load_plugin
Aug 14 18:47:12 cif cif-router[1717]:     self.store = self.store.Plugin(**kwargs)
Aug 14 18:47:12 cif cif-router[1717]:   File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0a22-py2.7.egg/cif/store/zelasticsearch/__init__.py", line 68, in __init__
Aug 14 18:47:12 cif cif-router[1717]:     self.indicators = IndicatorManager()
Aug 14 18:47:12 cif cif-router[1717]:   File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0a22-py2.7.egg/cif/store/zelasticsearch/indicator.py", line 33, in __init__
Aug 14 18:47:12 cif cif-router[1717]:     self.lockm = LockManager(self.handle, logger)
Aug 14 18:47:12 cif cif-router[1717]:   File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0a22-py2.7.egg/cif/store/zelasticsearch/locks.py", line 21, in __init__
Aug 14 18:47:12 cif cif-router[1717]:     self.nodes = self._nodes()
Aug 14 18:47:12 cif cif-router[1717]:   File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0a22-py2.7.egg/cif/store/zelasticsearch/locks.py", line 24, in _nodes
Aug 14 18:47:12 cif cif-router[1717]:     info = elasticsearch.client.NodesClient(self.handle).info()
Aug 14 18:47:12 cif cif-router[1717]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 73, in _wrapped
Aug 14 18:47:12 cif cif-router[1717]:     return func(*args, params=params, **kwargs)
Aug 14 18:47:12 cif cif-router[1717]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/nodes.py", line 21, in info
Aug 14 18:47:12 cif cif-router[1717]:     node_id, metric), params=params)
Aug 14 18:47:12 cif cif-router[1717]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 318, in perform_request
Aug 14 18:47:12 cif cif-router[1717]:     status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
Aug 14 18:47:12 cif cif-router[1717]:   File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 123, in perform_request
Aug 14 18:47:12 cif cif-router[1717]:     raise ConnectionError('N/A', str(e), e)
Aug 14 18:47:12 cif cif-router[1717]: ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fc2226ffb50>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fc2226ffb50>: Failed to establish a new connection: [Errno 111] Connection refused)

And the unauth log

> Aug 14 20:05:11 cif cif-router[1836]: 2017-08-14 20:05:11,727 - ERROR - cif.store[166][MainThread] - unauthorized

**Comment by wesyoung** [comment]
in cifv3, cif-store should create the tokens index automatically for you (same for indicators).

the errors make it seem like cif-store isn't able to connect to your elasticsearch service. you may want to double check that both the service is accessible through 127.0.0.1:9200 and/or fiddle with this var:

https://github.com/csirtgadgets/bearded-avenger/blob/master/cif/store/zelasticsearch/__init__.py#L12

if the service is running somewhere else...
