### ISSUE TITLE
Lack of feedback from the installation

### ISSUE THREAD

**Issue by arjunv** [csirtgadgets/bearded-avenger#351]
I've got the v3 up and running with elastic search. However, one thing in particular that has confused me a lot the silent nature of the server. It's virtually impossible for a novice to understand what exactly is the status of my server. Are all the services up and running. And most importantly about the fetching. Are all the sources being fetched? How often are the feeds being fetched? Were there any errors parsing the feeds?

Now I'm not hoping for a web interface isque Anomali Staxx, but it would have been nice to have some data from the API, may be just to access tokens with admin access.

The reason for this textburst is that I had my server running for two days now. I pimped it up for I had a little too much resources lying around. My stats looked like this:
```
$ curl http://127.0.0.1:9200/_cat/indices?pretty
green open indicators-2017.08 **-** 5 0 268957 0 146.4mb 146.4mb
green open tokens             ** 5 0     10 0  64.1kb  64.1kb
```
![capture](https://user-images.githubusercontent.com/718092/29739048-103ac69c-8a52-11e7-80d2-e226dd053777.PNG)

![capture2](https://user-images.githubusercontent.com/718092/29739050-172917b0-8a52-11e7-8eea-4b50403fa821.PNG)

I thought that everything was up and running smoothly. Then two days later `cif --tags malware` was still returning 500 entries, all ipv4 addresses from a single source. I increased the `CIF_HUNTER_THREADS` to `5` and the iptraffic is almost completely bind traffic (10+ a second). I don't even know what's going wrong here. 

Now that cif v3 is leaving alpha, may be the documentation and usability should be given a higher priority. At this rate, you guys will have v4 alpha before v3's documentation becomes production level.

However, I do believe in this project and I'll continue posting any and all issues I stumble on, and try my best to fix any that I can.

**Comment by wesyoung** [comment]
happy to accept PRs. there's always things that can be improved upon as we go:

https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki

this looks like you're running on ubuntu ~16 LTS, and most of your questions about (did something error) can be found with:

`$ journalctl -n 2000 -fu csirtg-*`

or

`$ journalctl -n 2000 -fu cif-*`

we didn't spend much time on managing system resources from the api itself, which may be an interesting set of PR if someone wants to spend time on it. again, more than happy to merge stuff (we follow https://rfc.zeromq.org/spec:42/C4/, which enables us to hit MERGE very quickly).

there is a `cif-tokens` command that probably needs to be re-flushed out in the CIFv3 book, which does access the /tokens api.

check out /etc/cif/ for the rules csirtg-smrt is pulling from. that's a whole different "book" in and of itself that needs to be written some day. the old book is here:

https://github.com/csirtgadgets/massive-octo-spice/wiki/The-CIF-Book

which may help fill in the gaps as we're starting to doc the softer spots.

.. and yes. we probably will have v4 alphas out well before the v3 doc is "production ready". that's how we get new ideas into the pipline while we're flushing out the softer spots of code that's been a bit more battle tested. we've always kinda done it like this.

like i said- always happy to accept good clean and precise PRs. :)
