### ISSUE TITLE
cif command syntax changed?

### ISSUE THREAD

**Issue by pyree** [csirtgadgets/bearded-avenger#352]
Using the command 
**cif --tags malware --itype ipv4**

i get a nice list of events as expected but omitting the tags option leads to an error
**cif --itype ipv4
2017-09-04 13:58:25,710 - INFO - cifsdk.client.client[189][MainThread] - setting feed flag by default, use --no-feed to override
2017-09-04 13:58:25,710 - ERROR - cifsdk.client.client[209][MainThread] - missing --tags [phishing|malware|botnet|scanner|pdns|whitelist|...]**

The system is Xubuntu 16.04 fully patched with a fresh installation of CIFv3 as given here
_https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/Ubuntu16LTS_

Is there another way to ask for a list of events with all tags ?

**Comment by wesyoung** [comment]
Try '--no-feed'

--
wes
wesyoung.me

**Comment by pyree** [comment]
Thanks but it this in sync with the documentation here?
https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/Where-do-I-start-Feeds

Wouldn't I loose the qualities of a feed (Deduplication e.a.)?

**Comment by wesyoung** [comment]
I think so. May need a PR to add in that functionality (not sure what we'd call it). The issue we had was new users not understanding these nuances by default and applying the feeds inappropriately, then harassing me :)

If you can come up with an elegant way around this (keeping the default as is) I'm happy to merge it :)

--
wes
wesyoung.me

**Comment by pyree** [comment]
I'm not sure if it would adhere to your concepts but i tried (by intuition) a wildcard for tags like so
**cif --tags * --itype ipv4**
to produce a feed with all available tags and the given itype, Maybe this would fit the expectations of other users as well.

**Comment by wesyoung** [comment]
did it work?

**Comment by pyree** [comment]
Not as i expected (or hoped)

**cif --tags * --itype ipv4**
**2017-09-05 17:42:14,968 - INFO - cifsdk.client.client[189][MainThread] - setting feed flag by default, use --no-feed to override
2017-09-05 17:42:14,970 - ERROR - cifsdk.client.client[231][MainThread] - HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /feed?itype=ipv4&tags=Desktop&tags=Documents&tags=Downloads&tags=Music&tags=Pictures&tags=Public&tags=Templates&tags=Videos&confidence=8&nolog=False&days=21&limit=50000 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff5ebf169d0>: Failed to establish a new connection: [Errno 111] Connection refused',))**

**Comment by pyree** [comment]
but wait...
there seems to be another problem causing this error

**Comment by wesyoung** [comment]
part of what i'm trying to do is actually PREVENT you from doing something like that out of the gate. what you may see happen is different types of tags with different confidence levels get applied to things where you may get many false positives.

for example:

one of the tags is "Unsolicited Commercial Email" or "uce", from here:

https://csirtg.io/users/csirtgadgets/feeds/uce-urls

which we give a confidence of "9" to (eg: we're pretty sure it came in as spam). that feed has a lot of known OK urls in there (eg: amazon.com, apple.com, etc). we are sure it came in as UCE, but you probably don't want to apply that feed to lets say, some sort of sinkhole- you could start inadvertently blocking amazon.com (just one example we've seen).

something in CIF are "bad", and some things are "interesting to look at".

does that make sense? i guess maybe we need an --tags-all thing that throws a warning out "you don't want to use this feed in a device" or something... cause my guess is, you'll do this and start blocking on it- then in 3mo start yelling at me cause amazon.com is in the feed :)

**Comment by pyree** [comment]
OK, i guess i understand the intention. 
Thanks for the explanation.

**Comment by wesyoung** [comment]
don't get me wrong- i totally get the idea (that's the way we had defaulted things in CIFv2), but i kept getting teh same hate mail over and over and over... so if there's an elegant way to solve this problem, i'm all ears... maybe `--tags-all-i-know-what-im-doing` or something :)

**Comment by pyree** [comment]
I think you are moving in the right direction. Your work deserves more popularity. But more popularity means more expectations, some contradictory. Evolution vs. compatibility e.g.

**Comment by wesyoung** [comment]
or, at-worst some better FAQs :)

gonna close this for now, keep think'n on it (defining use cases and local scenarios are always helpful) and maybe we'll come up with an elegant way to do it..
