### ISSUE TITLE
problem with e-mail with ?

### ISSUE THREAD

**Issue by kinomakino** [csirtgadgets/bearded-avenger#355]
With the default provider aper.yml, when doing the feed intake, the program shortens when it finds an email with the symbols ???

Thank you.

aceback (most recent call last):
  File "/usr/local/bin/csirtg-smrt", line 11, in <module>
    load_entry_point('csirtg-smrt==0.0.0a48', 'console_scripts', 'csirtg-smrt')()
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 450, in main
    'goback': goback
  File "/usr/local/lib/python2.7/dist-packages/csirtg_smrt/smrt.py", line 334, in _run_smrt
    raise e
csirtg_indicator.exceptions.InvalidIndicator: unknown itype for "**mutti?25@minsal.cl"**

**Comment by wesyoung** [comment]
ack- have to check it out. in "service" mode csirtg-smrt will skip "invalid indicators", it's only when you run it manually without the `--skip-invalid` flag that it'll raise these (so for testing, you'd know).

**Comment by wesyoung** [comment]
what does your aper.yml look like? it's not provided in CIFv3 by default anymore...

**Comment by wesyoung** [comment]
also- try this:

`$ pip install https://github.com/csirtgadgets/csirtg-indicator-py/archive/master.zip`

which is an updated version of the indicator library to deal with special chars in email addresses. 

https://github.com/csirtgadgets/csirtg-indicator-py/pull/115

seems to work at a cursory glance, let me know if it works for you..
