### ISSUE TITLE
Feed: Talos IP Blacklist Download

### ISSUE THREAD

**Issue by giovino** [csirtgadgets/bearded-avenger#364]
Talos offers a [IP Blacklist Download](https://talos-intelligence-site.s3.amazonaws.com/production/document_files/files/000/018/180/original/ip_filter.blf)

Reference:
"The IP Blacklist is automatically updated every 15 minutes and contains a list of known malicious network threats that are flagged on all Cisco Security Products."
https://talosintelligence.com/reputation

**Comment by wesyoung** [comment]
i looked at this once and decided against it [at the time], there were no timestamps and zero context around it. handn't had the cycles to try and vet it yet.

got a working yml config handy?
