### ISSUE TITLE
Unable to delete tokens with cif-token

### ISSUE THREAD

**Issue by sfinlon** [csirtgadgets/bearded-avenger#378]
# Expected behavior and actual behavior.
Running the following should delete a token, but it only displays the tokens in the system.
`# cif-tokens --delete-token 12345`

# Steps to reporduce the problem
Use `cif-tokens` to display the tokens in the system.
then use `cif-tokens --delete-token 12345`

# Specifications like the version of the project, operating system, or hardware.
Bearded Avenger 3.0.0b4

**Comment by sfinlon** [comment]
I also can't update a token. Whatever flags/order I put in there, it says 'token updated successfully' but it only erases the username and seemingly everything else.

`# cif-tokens
+-------------+----------+-------------------------+-------+-------+-------+------+---------+----------------------------------------------------------------------------------+
|   username  |  groups  |     last_activity_at    | admin |  read | write | acl  | expires |                                      token                                       |
+-------------+----------+-------------------------+-------+-------+-------+------+---------+----------------------------------------------------------------------------------+
|    scott    | everyone |           None          | False | False |  True |      |   None  | 12345 |
+-------------+----------+-------------------------+-------+-------+-------+------+---------+----------------------------------------------------------------------------------+

# cif-tokens --update 12345 --username scott --acl general
2018-01-12 10:05:27,985 - INFO - cifsdk.client.tokens[175][MainThread] - token updated successfully
+----------+---------------+------------------+-------+-------+-------+-----+---------+----------------------------------------------------------------------------------+
| username |     groups    | last_activity_at | admin |  read | write | acl | expires |                                      token                                       |
+----------+---------------+------------------+-------+-------+-------+-----+---------+----------------------------------------------------------------------------------+
|   None   | [u'everyone'] |       None       |  None | False |  None |     |   None  | 12345 |
+----------+---------------+------------------+-------+-------+-------+-----+---------+----------------------------------------------------------------------------------+

# cif-tokens --username scott --acl general --update 12345
2018-01-12 10:07:34,060 - INFO - cifsdk.client.tokens[175][MainThread] - token updated successfully
+----------+---------------+------------------+-------+-------+-------+-----+---------+----------------------------------------------------------------------------------+
| username | groups | last_activity_at | admin | read | write | acl | expires | token |
+----------+---------------+------------------+-------+-------+-------+-----+---------+----------------------------------------------------------------------------------+
| None | [u'everyone'] | None | None | False | None | | None | 12345 |
+----------+---------------+------------------+-------+-------+-------+-----+---------+----------------------------------------------------------------------------------+
root@cif:/etc/cif/rules/default# cif-tokens --update 12345 --username="scott"
2018-01-12 10:08:01,757 - INFO - cifsdk.client.tokens[175][MainThread] - token updated successfully
+----------+---------------+------------------+-------+-------+-------+-----+---------+----------------------------------------------------------------------------------+
| username | groups | last_activity_at | admin | read | write | acl | expires | token |
+----------+---------------+------------------+-------+-------+-------+-----+---------+----------------------------------------------------------------------------------+
| None | [u'everyone'] | None | None | False | None | | None | 12345 |
+----------+---------------+------------------+-------+-------+-------+-----+---------+----------------------------------------------------------------------------------+`

**Comment by wesyoung** [comment]
see if this fixes it (the you expected to call it):

```
$ pip install https://github.com/csirtgadgets/bearded-avenger-sdk-py/archive/fix/tokens.zip
$ cif-tokens --delete-token 12345
```

**Comment by sfinlon** [comment]
```
# cif-tokens --delete-token 12345
2018-01-16 16:36:28,263 - INFO - cifsdk.client.tokens[156][MainThread] - deleted: 1 tokens successfully
```
