### ISSUE TITLE
regex parsing

### ISSUE THREAD

**Issue by villain** [csirtgadgets/bearded-avenger#379]
i'm entirely sure this is my regex and not a bug, however;

i'm trying to store ja3 & ssl certs in CIF using existing otypes (md5 and sha1), but just adding tags for each type when doing queries. the csv's i'm trying to ingest look like:

CERT,ea8e4e7842a156eda3db4d5215efb1fd3bg2da16,,vawtrak,2016-08-21T00:00:00Z

csv headers are: type, cert hash, related md5 (optional), description, reporttime

the pattern i'm using in the cif config is: '^(CERT),(\S+),(.*),(.*),(\S+)$'

however the reporttime value is being assigned to description:

[2018-01-19T19:26:10,426Z][28862][DEBUG][CIF::Smrt:179]: $VAR1 = {'tags' => ['sslcert'],'observable' => 'ea8e4e7842a156eda3db4d5215efb1fd3bg2da16','group' => 'everyone','tlp' => 'amber','description' => '2016-08-21T00:00:00Z','parser' => 'regex','confidence' => '85','altid' => 'reporttime' => '2018-01-19T08:26:10Z','otype' => 'md5','provider' => 'internal'};

i'm guessing the issue is to do with the optional related md5 field, is there a better way to match something like the line above?

**Comment by wesyoung** [comment]
maybe try anchoring the hash, something like:

`^(CERT),([a-z0-9]+),,(\S+),(\S+)$`

(dunno what belongs in that blank ',,' so that may ruin my example)

https://regexr.com/3jfc4

**Comment by villain** [comment]
the blank would be a related md5 hash of a corresponding binary (if we have it)

**Comment by wesyoung** [comment]
so maybe something like:

`^(CERT),([a-z0-9]+),([a-z0-9]+)?,(\S+),(\S+)$`

(i use the osx Patterns.app, but lots of these things online these days to fiddle with)

**Comment by villain** [comment]
yep, ive tried all those. using regex101.com with the following regex it works;

^(CERT),([a-z0-9]+),(([a-z0-9]+)?),([\s\S]*),(\S+)$

but when its being parsed by cif, i'm not sure if that sometimes empty value is breaking something when its empty and being fields to be moved over by one or something. eg, what should be in reporttime is actually in the description field, and reporttime is empty(?)

**Comment by wesyoung** [comment]
is this CIFv2?

**Comment by wesyoung** [comment]
my guess is yes, you might be correct in that the sometimes null is breaking things

my next steps would be to test with https://github.com/csirtgadgets/csirtg-smrt-py and see if you get similar results. (csirtg-smrt-py is easier to 'fix' than in v2 for this kinda thing-). would have to think on it too, dunno that we've run into this kinda thing before..
