### ISSUE TITLE
Is there a way to make v3 use Elasticsearch instead of SQLite?

### ISSUE THREAD

**Issue by craigm-didata** [csirtgadgets/bearded-avenger#380]
I saw some references in the documentation that SQLite was the "default".  Is there a non-default option in the easybutton that will use Elasticsearch instead?

**Comment by wesyoung** [comment]
give this a shot:

https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/Ubuntu16LTS#elasticsearch
