### ISSUE TITLE
--asn returns all results with ES backend

### ISSUE THREAD

**Issue by sven342** [csirtgadgets/bearded-avenger#383]
cif version 3.0.0b5

cif --asn returns all results instead of specified ASN with ES datastore
ASN info is populated in ES backend

**Comment by wesyoung** [comment]
i have some other fixes i want to get in before the next release- thanks for this. if you wanna hot-fix it for now see:

https://github.com/csirtgadgets/bearded-avenger/pull/384/files#diff-292cdb1552daeade81bea1a3c22dd90a

just reload cif-router and you should be good to go.

you can ignore the update to csirtg.yml below that.
