### ISSUE TITLE
New Feeds Integration

### ISSUE THREAD

**Issue by shrishti01** [csirtgadgets/bearded-avenger#390]
Hi,
Hope you are doing well.
Please help me out with my query,
how is it possible to fetch feeds from honeypot implemented on different network from cifv3 ?

Thanks & Regards

**Comment by wesyoung** [comment]
depends on the honeypot. the easiest (non programming way) would be to write the honeypot logs out to a file and have csirtg-smrt parse that file as a feed. the programmer way would be to use the python SDK and submit the indicators via your honeypot logging framework:

https://github.com/csirtgadgets/bearded-avenger-sdk-py/wiki#submit

kind of like we do with cowrie and csirtg:

https://github.com/micheloosterhof/cowrie/blob/master/cowrie/output/csirtg.py#L79
