### ISSUE TITLE
confidence pulled from cifv2 not updated

### ISSUE THREAD

**Issue by sfinlon** [csirtgadgets/bearded-avenger#413]
# Do you have an active https://csirtg.io/support account ? :)
yes

# Expected behavior and actual behavior.
Feeds from CIFv2 should have their confidence converted to the CIFv3 1-10 scale 
+------------+----------------------+----------------------------+----------------+----------------------------+----------------------------+-------+--------------------+---------------+------------+-------+-----------------------+
|    tlp     |        group         |         reporttime         |   indicator    |         firsttime          |          lasttime          | count |        tags        |  description  | confidence | rdata | provider              |
+------------+----------------------+----------------------------+----------------+----------------------------+----------------------------+-------+--------------------+---------------+------------+-------+-----------------------+
| privileged | othergroup | 2018-08-16T08:16:56.00000Z | 66.240.236.119 | 2018-08-16T08:16:56.00000Z | 2018-08-16T08:16:56.00000Z |   1   |      scanner       | aggressive ip |    75.0    |  None | otherprovider |
|   green    |       everyone       | 2018-08-16T15:51:10.14261Z | 66.240.236.119 | 2018-08-16T07:55:03.00000Z | 2018-08-16T07:57:34.00000Z |   2   | bruteforce,scanner |      None     |    9.0     |  None | dataplane.org         |
+------------+----------------------+----------------------------+----------------+----------------------------+----------------------------+-------+--------------------+---------------+------------+-------+-----------------------+
# Steps to reporduce the problem
Pull a CIFv2 feed into CIFv3

# Specifications like the version of the project, operating system, or hardware.
CIF 3.0.0rc4

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/csirtg-smrt-py/pull/266
