### ISSUE TITLE
problem: multi-tags filter doesn't seem to work

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/bearded-avenger#421]
# Do you have an active https://csirtg.io/support account ? :)
yes

# Did you check the FAQ https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/FAQ ?
yes

# Are you running with hunters enabled? If so, does turning them off resolve the problem?
no

# Expected behavior and actual behavior.
multi tags only produces singe tag

```
$ cif --tags phishing,scanner,malware,bruteforce --itype ipv4
```

**Comment by vladoros** [comment]
Opened #430 to fix this, please review.
