### ISSUE TITLE
/u gives error 500

### ISSUE THREAD

**Issue by exitnode** [csirtgadgets/bearded-avenger#426]
Hi,

everything is working for me (fetching feeds, querying via the cli and API) except using the webui via http(s). A GET request to /u results in the following error:

> Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

The error log says:

> [2018-11-01 17:09:38,849] ERROR in app: Exception on /u [GET]
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python2.7/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
>     return cors_after_request(app.make_response(f(*args, **kwargs)))
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1610, in full_dispatch_request
>     rv = self.preprocess_request()
>   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1831, in preprocess_request
>     rv = func()
>   File "/usr/local/lib/python2.7/dist-packages/cif-3.0.0rc6-py2.7.egg/cif/httpd/__init__.py", line 201, in before_request
>     return render_template('login.html', code=401)
>   File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 133, in render_template
>     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
>   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 869, in get_or_select_template
>     return self.get_template(template_name_or_list, parent, globals)
>   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
>     return self._load_template(name, self.make_globals(globals))
>   File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
>     template = self.loader.load(self, name, globals)
>   File "/usr/local/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
>     source, filename, uptodate = self.get_source(environment, name)
>   File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 57, in get_source
>     return self._get_source_fast(environment, template)
>   File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 85, in _get_source_fast
>     raise TemplateNotFound(template)
> TemplateNotFound: login.html

I cannot find a file named login.html anywhere on the system.
The installation has been perormed via the EasyButton method on a vanilla Ubuntu 16.04.5 LTS server.

**Comment by ajt** [comment]
I pulled these templates out of the chrome plugin repo I think.

**Comment by exitnode** [comment]
> I pulled these templates out of the chrome plugin repo I think.

Thank you for your comment! I think i found them here: https://github.com/csirtgadgets/bearded-avenger/tree/master/cif/httpd/templates

Where in the filesystem did you drop them?

**Comment by sfinlon** [comment]
#434 should fix this.

**Comment by sfinlon** [comment]
> Where in the filesystem did you drop them?

But if you do a `cp -R /usr/local/src/bearded-avenger-master/cif/httpd/templates/  /usr/local/lib/python2.7/dist-packages/cif-3.0.0rc6-py2.7.egg/cif/httpd` 

From wherever you extract the tar to, and then follow through the steps to create the token and update the cif.env file and restart the services.

**Comment by sfinlon** [comment]
GUI was completely overhauled with PR #458
