### ISSUE TITLE
Feeds with confidence over 10

### ISSUE THREAD

**Issue by meetzoo** [csirtgadgets/bearded-avenger#431]
# Do you have an active https://csirtg.io/support account ? :)
No
# Did you check the FAQ https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/FAQ ?
Yes
# Are you running with hunters enabled? If so, does turning them off resolve the problem?
No
# Expected behavior and actual behavior.
Feeds have confidence over 10
# Steps to reporduce the problem
check out feeds
# Relevant logs as a result of the actual behavior
# https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/FAQ#searching-logs

# Did you attempt to fix the problem and submit a pull request?
no
# Specifications like the version of the project, operating system, or hardware.

# Does adding additional memory to the box resolve the problem?

# How large is your /var/lib/cif.sqlite database?

Feeds added in https://github.com/csirtgadgets/bearded-avenger/pull/429/files have the confidence level over 10(like cif v2), so now we have most providers with confidence between 1 and 10 and providers with confidence over 10(darklist_de.yml, normshield.yml, stopforumspam.yml)

**Comment by wesyoung** [comment]
fixed in rc8 ty!
