### ISSUE TITLE
problem: there is not stats interface (api, web ui)

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/bearded-avenger#46]
- internal tables
- by provider
- by country / asn / etc
- provide msg type, interface, etc
- cif-store should provide this and keep track of.

**Comment by giovino** [comment]
* total count of records
* percent difference in records vs than running average (7 day??)
* unparsed / unmatched records
  * you can imagine cif-smrt reporting on records that do not match parsing logic
    * when a data source adds a new type/tags

**Comment by wesyoung** [comment]
```
select provider, count(1) from indicators group by provider order by count(1) desc;
osint.bambenekconsulting.com|713329
reputation.alienvault.com|57436
|35760
dataplane.org|31051
ransomware.abuse.ch|10558
openphish.com|10069
csirtg.io|2979
isc.sans.edu|1997
spamhaus.org|884
malc0de.com|787
malwaredomains.com|739
vxvault.net|231
```
