### ISSUE TITLE
what is the password of cif?

### ISSUE THREAD

**Issue by yakoubiborhen** [csirtgadgets/bearded-avenger#526]
# Are you getting value from the project? Have you donated to the project?

https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=YZPQXDLNYZZ3W

# Did you check the FAQ https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/FAQ ?

# Are you running with hunters enabled? If so, does turning them off resolve the problem?

# Expected behavior and actual behavior.

# Steps to reporduce the problem

# Relevant logs as a result of the actual behavior
# https://github.com/csirtgadgets/bearded-avenger-deploymentkit/wiki/FAQ#searching-logs

# Did you attempt to fix the problem and submit a pull request?

# Specifications like the version of the project, operating system, or hardware.

# Does adding additional memory to the box resolve the problem?

# How large is your /var/lib/cif.sqlite database?

**Comment by yakoubiborhen** [comment]
where can i find the password of cif?

**Comment by mdavis332** [comment]
> where can i find the password of cif?

Whenever you start it up for the first time, it should automatically generate some tokens and save those in your chosen data store (sqlite or elastic). Query that data store for those tokens and the admin token should get you going.

**Comment by yakoubiborhen** [comment]
Thank you for your assistance,
It appeared that when i run the cmd ' sudo bash easybutton.sh'
it shows an error indicate that python3.5 not supported anymore , soo i'm
gonna solve that problem first , and after that i will check the tokens.btw
there a problem with the installation of sqlite with this error message 'E:
Failed to fetch
http://ppa.launchpad.net/jonathonf/backports/ubuntu/dists/xenial/main/binary-amd64/packages
404 Not Found [IP: 185.125.190.52 80]' .
Waiting for your reply.

Le jeu. 4 mai 2023 à 11:20, Michael Davis ***@***.***> a
écrit :

**Comment by wesyoung** [comment]
CIFv3 is ~10 years old and should probably be considered EOL. if you're starting from scratch- you should start here:

https://github.com/csirtgadgets/cif-v5

(even then, cifv5 is meant more to be a model for how to do some things, there are lots of newer projects out there that might be of use too, more actively developed: https://github.com/hslatman/awesome-threat-intelligence#frameworks-and-platforms)

**Comment by yakoubiborhen** [comment]
thank you for your assistance , i want to ask about cif-v5 , is it supporting Ubuntu 18 LTS Desktop version or server version?

**Comment by wesyoung** [comment]
server

**Comment by yakoubiborhen** [comment]
Thank you

**Comment by yakoubiborhen** [comment]
Hello , can you give me a guide for installing cif-v5 coz i faced problem with make docker-tag , coz my purpose is after validate the installation i want to test the data format in the output .
Thank you for your understanding.

**Comment by yakoubiborhen** [comment]
is the problem of elasticsearch still persist ?
