### ISSUE TITLE
Multiple failures when following quickstart guide

### ISSUE THREAD

**Issue by JesseBowling** [csirtgadgets/bearded-avenger#67]
* Failure because pip not present
* Failure pip install -r requirements.txt not run with sudo, Python.h unavailable

Solution:
sudo apt-get install python-pip python-dev
sudo pip install -r requirements.txt

**Comment by wesyoung** [comment]
were you using the Ubuntu14 guide? or the one from the readme?

**Comment by JesseBowling** [comment]
readme.md

Should I easybutton.sh instead on Ubuntu 14?

**Comment by wesyoung** [comment]
Yes. The QuickStart assumes you've got Python dev and pip all setup. I'll add a hint to the guides though to help deconflict. Makes sense?

**Comment by JesseBowling** [comment]
Works for me!

**Comment by wesyoung** [comment]
I mean a hint to the read me pointing at the guides

**Comment by JesseBowling** [comment]
Using:
:~/bearded-avenger$ sudo bash deployment/easybutton.sh 
Checking for an Internet connection
http://github.com appears to be available via HTTP
sudo: add-apt-repository: command not found

Fix for me:

$ sudo apt-get install software-properties-common

Afterwards it runs just fine.

**Comment by wesyoung** [comment]
Ah. I was using vagrant to test they must include that in their base box..
